version: '3.1'
services:

  adminer:  #Optional for accessing databases
    # How to connect to web UI
    # Server: NAME_OF_YOUR_POSTGRES_SERVER in our case it's postgres-server
    # Username: DB_USERNAME
    # Password: DB_PASSWORD
    # Database: NAME_OF_ZABBIX_DB
    image: adminer
    restart: always
    ports:
      - 8080:8080

  grafana-server: #optional more functional and creative UI
    # image: grafana/grafana:latest  # Bad for stability
    image: grafana/grafana:8.2.0
#    volumes:
#      - /etc/ssl/grafana:/etc/ssl/grafana:ro
#      - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    restart: always
    #links:
    #  - zabbix-pgsql

  portainer:
    image: portainer/portainer-ce:2.9.0
    volumes:
#      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: always
