services:
  reverse-proxy-nginx:
    image: nginx:latest
#    volumes:
#      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      zabbix-docker_zbx_net_backend:
      zabbix-docker_zbx_net_frontend:
    restart: always

  certbot:
    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
    networks:
      zabbix-docker_zbx_net_backend:
      zabbix-docker_zbx_net_frontend:

networks:
  zabbix-docker_zbx_net_frontend:
    external: true
  zabbix-docker_zbx_net_backend:
    external: true